apiVersion: v1
data:
  port: "8080"
  mysql: "root:dfjns@tcp(mariadb.aaa:3306)/test?parseTime=true"
  mongo: "mongodb://mongo.aaa:27017/test"
kind: ConfigMap
metadata:
  labels:
    app: config
  name: config
---
apiVersion: v1
kind: Service
metadata:
  name: a1
spec:
  ports:
  - name: tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: test
    port: 3000
    protocol: TCP
    targetPort: 3000
  type: LoadBalancer
  selector:
    app: a1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: a1
    spec:
      containers:
      - image: arieswangdocker/microservice:latest
        imagePullPolicy: Always
        name: a1
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 3000
          protocol: TCP
        envFrom:
        - configMapRef:
            name: config

 